"""Environment-file CLI commands."""

##############################################################################
# Python imports.
from __future__ import annotations

from pathlib import Path
from typing import Any, get_args, get_origin

##############################################################################
# Typer imports.
import typer

##############################################################################
# Dotenv imports.
from dotenv import set_key, unset_key

##############################################################################
# Pydantic imports.
from pydantic import ValidationError

##############################################################################
# Local imports.
from ..data import (
    RuntimeSettings,
    environment_file,
    environment_variable_names,
    load_environment_values,
    load_runtime_settings,
)
from ..data.settings import runtime_settings_from_file
from .common import apply_runtime_path_overrides, config_path_option, env_path_option

##############################################################################
app = typer.Typer(
    help="Manage Hike runtime environment variables.",
    add_completion=True,
    no_args_is_help=True,
)


##############################################################################
def _fail(message: str, code: int = 1) -> None:
    """Exit the CLI with an error message."""
    typer.secho(message, fg=typer.colors.RED, err=True)
    raise typer.Exit(code=code)


##############################################################################
def _primary_env_name(field_name: str) -> str:
    """Return the primary environment variable name for a field."""
    return environment_variable_names(field_name)[0]


##############################################################################
def _type_name(annotation: Any) -> str:
    """Return a human-readable type name."""
    origin = get_origin(annotation)
    if origin is None:
        if annotation is str or annotation is Path:
            return "string"
        if annotation is bool:
            return "boolean"
        return getattr(annotation, "__name__", str(annotation))
    if str(origin) in {"typing.Union", "types.UnionType"}:
        return " | ".join(_type_name(item) for item in get_args(annotation))
    return str(origin)


##############################################################################
def _render_env_template(example: bool = False) -> str:
    """Render a commented .env file template from the runtime settings model."""
    defaults = load_runtime_settings().model_dump(mode="json", exclude_none=False)
    lines = [
        "# ---------------------------------------------------------------------------",
        "# Hike environment settings — generated by `hike env init`",
        "# ---------------------------------------------------------------------------",
        "",
    ]
    for name, field in RuntimeSettings.model_fields.items():
        env_names = environment_variable_names(name)
        primary_name = env_names[0]
        lines.append(f"# {field.description or f'Configure {primary_name}.'}")
        lines.append(f"# Type:    {_type_name(field.annotation)}")
        if len(env_names) > 1:
            lines.append(f"# Aliases: {', '.join(env_names[1:])}")
        default = defaults.get(name)
        if default is None:
            lines.append(
                "# OPTIONAL — uncomment and set a value to override the default"
            )
            lines.append(f"# {primary_name}=")
        else:
            lines.append(f"# Default: {default}")
            value = "" if example else default
            lines.append(f"{primary_name}={value}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


##############################################################################
@app.command("init")
def init_env(
    force: bool = typer.Option(
        False,
        "--force",
        help="Overwrite an existing environment file.",
    ),
    example: bool = typer.Option(
        False,
        "--example",
        help="Write placeholder values instead of resolved current values.",
    ),
    config_path: Path | None = config_path_option(),
    env_path: Path | None = env_path_option(),
) -> None:
    """Create a commented environment file."""
    apply_runtime_path_overrides(config_path, env_path)
    target = environment_file()
    if target.exists() and not force:
        _fail(f"Environment file already exists: {target}", code=1)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_render_env_template(example=example), encoding="utf-8")
    typer.echo(f"Created environment file: {target}")


##############################################################################
@app.command("show")
def show_env(
    reveal: bool = typer.Option(
        False,
        "--reveal",
        help="Show values without redaction.",
    ),
    config_path: Path | None = config_path_option(),
    env_path: Path | None = env_path_option(),
) -> None:
    """Display the current environment file contents."""
    apply_runtime_path_overrides(config_path, env_path)
    values = load_environment_values()
    for field_name in RuntimeSettings.model_fields:
        env_names = environment_variable_names(field_name)
        value = next((values.get(name) for name in env_names if name in values), None)
        display = value if reveal or value is None else "***"
        typer.echo(f"{env_names[0]}={display if display is not None else ''}")


##############################################################################
@app.command("list")
def list_env(
    config_path: Path | None = config_path_option(),
    env_path: Path | None = env_path_option(),
) -> None:
    """List supported environment variables."""
    apply_runtime_path_overrides(config_path, env_path)
    for field_name, field in RuntimeSettings.model_fields.items():
        names = environment_variable_names(field_name)
        typer.echo(f"{names[0]}\t{field.description}")


##############################################################################
@app.command("get")
def get_env(
    variable: str = typer.Argument(..., help="Environment variable name."),
    config_path: Path | None = config_path_option(),
    env_path: Path | None = env_path_option(),
) -> None:
    """Get a value from the environment file."""
    apply_runtime_path_overrides(config_path, env_path)
    values = load_environment_values()
    if variable not in values:
        _fail(f"Environment variable not found: {variable}", code=1)
    typer.echo(values[variable])


##############################################################################
@app.command("set")
def set_env(
    variable: str = typer.Argument(..., help="Environment variable name."),
    value: str = typer.Argument(..., help="Environment variable value."),
    config_path: Path | None = config_path_option(),
    env_path: Path | None = env_path_option(),
) -> None:
    """Set a value in the environment file."""
    apply_runtime_path_overrides(config_path, env_path)
    target = environment_file()
    target.parent.mkdir(parents=True, exist_ok=True)
    set_key(str(target), variable, value)
    try:
        runtime_settings_from_file(target)
    except ValidationError as error:
        _fail(str(error), code=1)
    typer.echo(f"Set {variable}")


##############################################################################
@app.command("unset")
def unset_env_value(
    variable: str = typer.Argument(..., help="Environment variable name."),
    config_path: Path | None = config_path_option(),
    env_path: Path | None = env_path_option(),
) -> None:
    """Unset a value in the environment file."""
    apply_runtime_path_overrides(config_path, env_path)
    target = environment_file()
    if not target.exists():
        _fail(f"Environment file not found: {target}", code=1)
    unset_key(str(target), variable)
    typer.echo(f"Unset {variable}")


##############################################################################
@app.command("validate")
def validate_env(
    config_path: Path | None = config_path_option(),
    env_path: Path | None = env_path_option(),
) -> None:
    """Validate the current environment file."""
    apply_runtime_path_overrides(config_path, env_path)
    target = environment_file()
    if target.exists():
        try:
            runtime_settings_from_file(target)
        except ValidationError as error:
            _fail(str(error), code=1)
    typer.echo(f"Environment settings are valid: {target}")


##############################################################################
@app.command("path")
def env_path_cmd(
    config_path: Path | None = config_path_option(),
    env_path: Path | None = env_path_option(),
) -> None:
    """Print the effective environment-file path."""
    apply_runtime_path_overrides(config_path, env_path)
    typer.echo(environment_file())


### env_cmd.py ends here
