site_name: Hike
docs_dir: docs/source/
site_url: https://tobiashochguertel.github.io/hike/
repo_url: https://github.com/tobiashochguertel/hike
repo_name: tobiashochguertel/hike

nav:
  - "Getting Started": index.md
  - "CLI Reference": cli.md
  - "In-App Command Line": commands.md
  - "Configuration":
      - "Overview": configuration.md
      - "Files, Environment & Schemas": configuration-files-and-environment.md
      - "Keybindings": configuration-keybindings.md
      - "File Browser & Startup": configuration-file-browser-and-startup.md
      - "UI, Layout & Content": configuration-ui-and-content.md
  - "License": license.md
  - "Change Log": changelog.md

plugins:
  - search
  - markdown-exec:
      ansi: required
      languages:
        - bash

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - markdown.extensions.attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg

theme:
  name: material
  icon:
    logo: fontawesome/brands/markdown
  features:
    - content.code.copy
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tobiashochguertel/hike

### mkdocs.yml ends here
