site_name: Hike
docs_dir: docs/source/
repo_url: https://github.com/davep/hike

nav:
  - "Guide": index.md

markdown_extensions:
  - admonition
  - pymdownx.snippets

theme:
  name: material
  features:
    - content.code.copy
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

### mkdocs.yml ends here
