name: Code quality tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - feature/all-requested-features
  pull_request:

jobs:

  style-lint-and-test:

    name: Style, lint, test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.12.0"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          echo ${{ matrix.python-version }} > .python-version
          make setup

      - name: Check for typos
        run: make spellcheck

      - name: Check the Code style
        run: make codestyle

      - name: Lint the code
        run: make lint

      - name: Type check the code
        run: make stricttypecheck

      - name: Run unit tests
        run: make test

### style-lint-and-test.yaml ends here
